name: Build v2rayA feed

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    name: Build packages for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: mips_24kc
            runtime_test: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: immortalwrt/gh-action-sdk@v4.1
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: v2raya_ci
          PACKAGES: ca-certificates v2ray-core
          NO_REFRESH_CHECK: 1

      - name: Move created packages to project dir
        run: cp bin/packages/${{ matrix.arch }}/v2raya_ci/*.ipk . || true

      - name: Store packages
        uses: actions/upload-artifact@v3
        if: github.event_name != 'release'
        with:
          name: ${{ matrix.arch }}-${{ github.sha }}-packages
          path: "*.ipk"